[project]
name = "wealth-health"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipywidgets>=8.1.5",
    "matplotlib>=3.9.2",
    "numpy>=2.1.3",
    "salib>=1.5.1",
    "seaborn>=0.13.2",
    "tqdm>=4.67.0",
]
